name: CD

on:
  push:
    branches: develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy
        run: |
          sudo docker stop final
          sudo docker rm final
          sudo docker rmi final
          sudo docker system prune --force
          sudo docker build . -t final
          sudo docker run --name final -d -p 3300:3300 -it final
